<a href="https://colab.research.google.com/github/karthik270403/leetcode/blob/main/data_cleaning_using_numpy_and_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("/content/Data-cleaning-for-beginners-using-pandas.csv",index_col=0)

In [4]:
df.head()

        Age     Salary  Rating       Location  Established Easy Apply
Index
0      44.0  $44k-$99k     5.4       India,In         1999       TRUE
1      66.0  $55k-$66k     3.5    New York,Ny         2002       TRUE
2       NaN  $77k-$89k    -1.0    New York,Ny           -1         -1
3      64.0  $44k-$99k     4.4       India In         1988         -1
4      25.0  $44k-$99k     6.4  Australia Aus         2002         -1

In [5]:
df.tail()

        Age     Salary  Rating       Location  Established Easy Apply
Index
24     13.0  $44k-$99k    -1.0    New York,Ny         1987         -1
25     55.0  $44k-$99k     0.0  Australia Aus         1980       TRUE
26      NaN  $55k-$66k     NaN       India,In         1934       TRUE
27     52.0  $44k-$99k     5.4       India,In         1935         -1
28      NaN  $39k-$88k     3.4  Australia Aus         1932         -1

In [6]:
df.shape

(29, 6)

In [7]:
df.describe()

             Age     Rating  Established
count  22.000000  28.000000    29.000000
mean   39.045455   3.528571  1638.620690
std    16.134781   2.825133   762.079599
min    13.000000  -1.000000    -1.000000
25%    25.000000   1.050000  1935.000000
50%    39.500000   4.200000  1984.000000
75%    50.000000   5.400000  1999.000000
max    66.000000   7.800000  2020.000000

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 29 entries, 0 to 28
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Age          22 non-null     float64
 1   Salary       29 non-null     object
 2   Rating       28 non-null     float64
 3   Location     29 non-null     object
 4   Established  29 non-null     int64
 5   Easy Apply   29 non-null     object
dtypes: float64(2), int64(1), object(3)
memory usage: 1.6+ KB

In [9]:
print('Total sum of Null values in data: ', df.isnull().sum().sum())
print()
print(df.isnull().sum())

Total sum of Null values in data:  8

Age            7
Salary         0
Rating         1
Location       0
Established    0
Easy Apply     0
dtype: int64

In [10]:
df.columns = df.columns.str.lower().str.replace(" ", "_")
df.columns

Index(['age', 'salary', 'rating', 'location', 'established', 'easy_apply'], dtype='object')

In [11]:
print(df.age.mean())

df['age'] = df.age.fillna(df.age.mean())
df['age'] = df.age.round(decimals=0)

print(df.age.isnull().sum())

39.04545454545455
0

In [12]:
df.head()

        age     salary  rating       location  established easy_apply
Index
0      44.0  $44k-$99k     5.4       India,In         1999       TRUE
1      66.0  $55k-$66k     3.5    New York,Ny         2002       TRUE
2      39.0  $77k-$89k    -1.0    New York,Ny           -1         -1
3      64.0  $44k-$99k     4.4       India In         1988         -1
4      25.0  $44k-$99k     6.4  Australia Aus         2002         -1

In [13]:
df["established"] = df["established"].replace(-1,np.nan)
df["established"].fillna('Unknown', inplace=True)

In [15]:
df.location.astype

<bound method NDFrame.astype of Index
0          India,In
1       New York,Ny
2       New York,Ny
3          India In
4     Australia Aus
5          India,In
6       New York,Ny
7     Australia Aus
8       New York,Ny
9          India,In
10         India,In
11         India,In
12         India,In
13    Australia Aus
14    Australia Aus
15    Australia Aus
16         India,In
17      New York,Ny
18      New York,Ny
19      New York,Ny
20      New York,Ny
21      New York,Ny
22      New York,Ny
23      New York,Ny
24      New York,Ny
25    Australia Aus
26         India,In
27         India,In
28    Australia Aus
Name: location, dtype: object>

In [16]:
df['location']= df['location'].str.replace("Australia Aus", "Australia, Aus")
df['location_city'] = df['location'].str.split(",", expand=True).get(0)
df['city_sign'] = df['location'].str.split(",", expand=True).get(1)
df.drop('location', inplace=True, axis=1)

In [17]:
df['rating'] = df["rating"].replace(-1,np.nan)
df['rating'] = df["rating"].fillna(df['rating'].mean()).round(decimals=1)

In [18]:
df['easy_apply'] = df['easy_apply'].replace("-1", "False")

In [19]:
df['salary'].iloc[0]

df['salary'] = df['salary'].apply(lambda x:x.replace("$",''))
df['salary'] = df['salary'].apply(lambda x:x.replace("k",''))

In [20]:
df

        age  salary  rating established easy_apply location_city city_sign
Index
0      44.0   44-99     5.4      1999.0       TRUE         India        In
1      66.0   55-66     3.5      2002.0       TRUE      New York        Ny
2      39.0   77-89     4.3     Unknown      False      New York        Ny
3      64.0   44-99     4.4      1988.0      False      India In      None
4      25.0   44-99     6.4      2002.0      False     Australia       Aus
5      44.0   77-89     1.4      1999.0       TRUE         India        In
6      21.0   44-99     0.0     Unknown      False      New York        Ny
7      44.0   44-99     4.3     Unknown      False     Australia       Aus
8      35.0   44-99     5.4     Unknown      False      New York        Ny
9      22.0   44-99     7.7     Unknown       TRUE         India        In
10     55.0   10-49     5.4      2008.0       TRUE         India        In
11     44.0   10-49     6.7      2009.0      False         India        In
12     39.0   44-99     0.0      1999.0      False         India        In
13     25.0   44-99     4.3      2019.0       TRUE     Australia       Aus
14     66.0   44-99     4.0      2020.0       TRUE     Australia       Aus
15     44.0  88-101     3.0      1999.0      False     Australia       Aus
16     19.0   19-40     4.5      1984.0      False         India        In
17     39.0   44-99     5.3      1943.0       TRUE      New York        Ny
18     35.0   44-99     6.7      1954.0       TRUE      New York        Ny
19     32.0   44-99     3.3      1955.0       TRUE      New York        Ny
20     39.0   44-99     5.7      1944.0       TRUE      New York        Ny
21     35.0   44-99     5.0      1946.0      False      New York        Ny
22     19.0   55-66     7.8      1988.0       TRUE      New York        Ny
23     39.0   44-99     2.4      1999.0       TRUE      New York        Ny
24     13.0   44-99     4.3      1987.0      False      New York        Ny
25     55.0   44-99     0.0      1980.0       TRUE     Australia       Aus
26     39.0   55-66     4.3      1934.0       TRUE         India        In
27     52.0   44-99     5.4      1935.0      False         India        In
28     39.0   39-88     3.4      1932.0      False     Australia       Aus

# CHIPOTLE

In [21]:
import numpy as np
import pandas as pd

In [34]:
df = pd.read_csv("/content/Data Cleaning with numpy and pandas - Dataset 2.csv")

In [35]:
df.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [36]:
df.tail()

,order_id,quantity,item_name,choice_description,item_price
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [37]:
df.shape

(4622, 5)

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.7+ KB

In [39]:
df.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

In [40]:
c = df.groupby('item_name').sum()
c = c.sort_values(['quantity'], ascending = False)
c.head()

,order_id,quantity,choice_description,item_price
item_name,,,,
Chicken Bowl,713926,761,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98$10.98$11.25$8.75$8.49$11.25$8.75$8.75$8...
Chicken Burrito,497303,591,"[Tomatillo-Green Chili Salsa (Medium), [Pinto ...",$8.49$8.49$10.98$8.49$10.98$10.98$8.75$10.98$8...
Chips and Guacamole,449959,506,0,$4.45$4.45$4.45$4.45$4.45$3.99$4.45$3.99$4.45$...
Steak Burrito,328437,386,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75$9.25$8.99$11.75$8.99$8.99$8.99$8.99$8.9...
Canned Soft Drink,304753,351,[Coke][Sprite][Coke][Coke][Lemonade][Sprite][D...,$1.25$1.25$1.25$1.25$1.25$1.25$1.25$1.25$1.25$...

In [41]:
c = df.groupby('choice_description').sum()
c = c.sort_values(['quantity'], ascending = False)
c.head(1)

,order_id,quantity,item_name,item_price
choice_description,,,,
[Diet Coke],123455,159,Canned SodaCanned SodaCanned Soda6 Pack Soft D...,$2.18$1.09$1.09$6.49$2.18$1.25$1.09$6.49$6.49$...

In [42]:
total_items_ordered = df.quantity.sum()
total_items_ordered

4972

In [43]:
df["item_price"]= df["item_price"].str.replace('$','').astype(float)
df

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75

In [44]:
revene= df['item_price'].sum()
print('Revenue was: $',revene)

Revenue was: $ 34500.16

In [45]:
orders = df.order_id.value_counts().count()
orders

1834

In [50]:
# Convert 'item_price' to string before using .str accessor
df["item_price"] = df["item_price"].astype(str).str.replace('[^\d.]', '', regex=True).astype(float)

# Calculate revenue for each item
df['revenue'] = df['quantity'] * df['item_price']

# Group by order_id and calculate total revenue per order
order_grouped = df.groupby(by=['order_id']).sum()

# Calculate the mean revenue per order
mean_revenue = order_grouped['revenue'].mean()
print(mean_revenue)

21.39423118865867

In [51]:
df.item_name.value_counts().count()

50